### ISSUE TITLE
Support for Metaboscape 5.0

### ISSUE THREAD

**Issue by chanana** [CCMS-UCSD/GNPS_Workflows#619]
**Describe the bug**
The Metaboscape 5.0 export format for the `msmsonly_featuretable` is different from the [example file](https://github.com/CCMS-UCSD/GNPSDocumentation/blob/master/docs/tutorials/AG_tutorial_files/MetaboScape-GNPS-Coffee_Tutorial_msmsonly_featuretable.csv).

Briefly,
- there are no extensions in the column headers
- right click menu does not have an "Export for GNPS" option. It is only present in the export menu button on the left side (screenshots below).   
There may be other differences; I just picked a few. I'm not sure why but this somehow affects the QIIME2 visualization where weird column names show up in the 3D PCoA plot.

**To Reproduce**
1. Go to [the job.](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=1d0d2f2a47ff4c8a8364abf6c42d62a9)
2. Click on `View qiime2 Emperor Plots`.
3. In `Color` tab select `scatter: filename` 
4. See the first 15 or so lines named with `MeanIntensity.d` that were part of the `msms-only` file but not the metadata.

**Alternative reproduction**
1. Alternatively, click on [download emperor data](https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=1d0d2f2a47ff4c8a8364abf6c42d62a9&view=download_emperor_data) on the [job finished page](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=1d0d2f2a47ff4c8a8364abf6c42d62a9).

**Expected behavior**
I expected only the categories I defined to show up.

**Screenshots**
Screenshot showing the Metaboscape 5.0 interface:
![image](https://user-images.githubusercontent.com/15051933/95664385-fa319a80-0b0c-11eb-8653-cbf6bc27cd24.png)
compared to the tutorial screenshot. 

**Additional context**
N/A

**Comment by chanana** [comment]
I am happy and willing to help write and / or update the Metaboscape 5 documentation if needed!

**Comment by mwang87** [comment]
Thanks for the update! This is great information. Definitely very helpful as we originally wrote documentation specifically for Metaboscape 2.0 rather than 5.0. I think what we could do is update the documentation (your help would be super appreciated! docs here: https://ccms-ucsd.github.io/GNPSDocumentation/gnps_community/#updating-the-gnps-documentation-quick). 

On the software side we can take your example and try to support both old (2.0) and new (5.0) output files.

**Comment by chanana** [comment]
Thanks, Ming! I can try to run the coffee example if you'd prefer that? It'll be more consistent with the already present examples? Otherwise, I can generate a smaller subset of data for you to use as an example? Some of data is not yet ready for the public domain since it technically belongs to a collaborator.

As for the documentation, I'll try and get to it ASAP! Thanks for your willingness to bring this all on board

**Comment by fzubeil-bdal** [comment]
Hi chanana,

thanks for bringing this up! Indeed it depends on the MetaboScape version, since 5.0 we also export the mean intensities of the groups defined in MetaboScape as well as the maximum intensity over all groups. The idea is to make it easier to plot the mean group intensities in CytoScape using this attribute as i.e. pie charts and detect if the intensity is high enough to assess if purification for i.e. NMR is feasable using max intensity.

I am also in the process of updating the manual (https://github.com/fzubeil-bdal/GNPSDocumentation/blob/master/docs/featurebasedmolecularnetworking-with-metaboscape.md) and will send a pull request soon.
