### ISSUE TITLE
FBMN with OpenMS files

### ISSUE THREAD

**Issue by eeko-kon** [CCMS-UCSD/GNPS_Workflows#781]
Hi! 

I am using an OpenMS workflow for feature identification and also generating the correct files using GNPSExport and TextExporter to introduce to FBMN. Even though my Feature Quantification table is in the right format, I detected an issue in cytoscape: all feature charges are zero. Is this normally shown like this in cytoscape? (e.g. I can also see only the precursor mass -aka charge zero- M). I am simply worried that two different networks were not connected because of this - possibly - missing info.

To reproduce and check the files:

https://doi.org/10.5281/zenodo.5546542

GNPS run:

https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=8f31f67b328c4710a587ebfeec32b970

Thank you!

**Comment by lfnothias** [comment]
Hi @eeko-kon,
Thanks a lot for providing the informations and files.

When using the FBMN workflow, the charge parsed by GNPS is derived from the MGF field e.g. `CHARGE=1+`.
Looking at the MGF file from OpenMS you shared. The charge field is fine. So maybe it has to do with some unusual fields in the MGF like that prevent the correct parsing: 
```
OUTPUT=
FILE_INDEX=
```
The best would be to have @mwang87 insight. Otherwise, you can try deleting these unusual MGF file fields. Note that the charge is just descriptive in the network and does not influence the network topology.

**Comment by mwang87** [comment]
One thing I think that also might be amiss, there are inconsistent delimiters in the metadata.tsv file. Can you check that file?

**Comment by eeko-kon** [comment]
Ming, I will correct the metadata and re-run it - will let you know the outcome! I am guessing that the "unusual" fields shouldn't be a problem, but I will delete those and create a separate job.

**Comment by eeko-kon** [comment]
**Updates**: 

corrected the metadata table - still zero charges everywhere and identical results after re-run

corrected metadata and mgf files - still zero charges everywhere and identical results after re-run

**Comment by mwang87** [comment]
I think you were trying to format an mzmine table but selected openms as the format? Can you check?

**Comment by eeko-kon** [comment]
Hey, no it's an openms table for sure :)

**Comment by mwang87** [comment]
Cool swing by gnps office hours and we can take a look together.

**Comment by eeko-kon** [comment]
Deal, see you tomorrow :)
